<?php

$CFG = array(
	'site_name'              => "Your Site Name",
	'root_url'               => "domain.com",
	'link_domains'           => "",
	'db_driver'              => "mysql",
	'db_host'                => "localhost",
	'db_user'                => "user",
	'db_pass'                => "password",
	'db_db'                  => "dbname",
	'cookie_prefix'          => "sitename_",
	'cookie_path'            => "/",
	'cookie_domain'          => ".domain.com",
	'db_pfx'                 => "tsms",
	'admin_email'            => "",
	'template_path'          => "template",
	'template_default'       => 2,
	'blacklist'              => "",
	'whitelist'              => "",
	'emaillist'              => "",
	'default_order_by'       => "d",
	'default_order'          => "d",
	'default_pagesize'       => 20,
	'acp_access'             => 1,
	'banned_access'          => 10,
	'guest_access'           => 4,
	'date_time_format'       => "M j Y, g:i A",
	'date_format'            => "M j Y",
	'date_short'             => "m/d/y",
	'max_icon_dims'          => "80x80",
	'def_icon_dims'          => "80x80",
	'default_icon'           => "https://mfgg.net/template/images/tcsms_icon.png",
	'default_icon_defective' => "https://mfgg.net/template/images/tcsms_icon_defective.png",
	'staff_name'             => "<i>Site Staff</i>",
	'site_offline'           => "0",
	'offline_msg'            => "The MFGG mainsite will be down for a few minutes during database maintenance.",
	'news_update_span'       => 14,
	'adm_virus_check'        => 1,
	'panel_expand'           => 1,
	'panel_maximize'         => 1,
	'quote_nesting'          => 0,
	'mail_out'               => "",
	'mail_interface'         => "sendmail",
	'smtp_host'              => "",
	'smtp_port'              => "25",
	'smtp_user'              => "",
	'smtp_pass'              => "",
	'max_consec_dl'          => 3,
	'cat_order'              => array(
		'0' => "1",
		'4' => "9,10",
	),
);

?>